---
title: "p8105_hw3_hz3023"
author: "Huiyi Zhu"
date: "2025-10-12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prepare
```{r}
library(ggridges)
library(tidyverse)
```

## Problem 1
```{r cars}

library(p8105.datasets)
data("instacart")
view("instacart") 
```
In this dataset, there are `r nrow(instacart)` observations and `r ncol(instacart)` variables. Key variable include the order id, product id, reordered times, user id and order number and others.

```{r}
instacart |>
  group_by(aisle) |>
  summarize(
    items = n()) |>
  mutate(
    aisle_ranking = min_rank(items)) |> 
  arrange(aisle_ranking)
```
There are 143 aisles in the data set. The most items ordered from fresh vegetables aisles.

Below is a bar polt show the number orderd in each aisle.
```{r}
instacart |>
  group_by(aisle) |>
  summarize(items = n()) |>
  filter(items > 10000) |>
ggplot(aes(x = aisle, y = items)) +
  geom_col()+
    coord_flip()
ggsave("p8105_hw1p1_barpolt.pdf")
```

```{r}
instacart |>
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) |>
  group_by(aisle, product_name) |>
  summarize(orders = n()) |> 
  knitr::kable()
```

```{r}
instacart |>
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) |>
  group_by(product_name, order_dow) |>
  summarize(mean_hour = mean(order_hour_of_day)) |>
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour) |>
  knitr::kable(digits = 1)
```

## Problem 2
```{r}

```

